queosk/build.gradle
queosk/src/main/java/com/bttf/queosk/QueoskApplication.java
queosk/src/main/java/com/bttf/queosk/config/BaseTimeEntity.java
queosk/src/main/java/com/bttf/queosk/config/JpaAuditingConfiguration.java
queosk/src/main/java/com/bttf/queosk/domain/enumerate/LoginApi.java
queosk/src/main/java/com/bttf/queosk/domain/enumerate/MenuStatus.java
queosk/src/main/java/com/bttf/queosk/domain/enumerate/OperationStatus.java
queosk/src/main/java/com/bttf/queosk/domain/enumerate/OrderStatus.java
queosk/src/main/java/com/bttf/queosk/domain/enumerate/RestaurantCategory.java
queosk/src/main/java/com/bttf/queosk/domain/enumerate/TableStatus.java
queosk/src/main/java/com/bttf/queosk/domain/enumerate/UserStatus.java
queosk/src/main/java/com/bttf/queosk/domain/enumerate/Verified.java
queosk/src/main/java/com/bttf/queosk/entity/MenuEntity.java
queosk/src/main/java/com/bttf/queosk/entity/OrderEntity.java
queosk/src/main/java/com/bttf/queosk/entity/RestaurantEntity.java
queosk/src/main/java/com/bttf/queosk/entity/TableEntity.java
queosk/src/main/java/com/bttf/queosk/entity/UserEntity.java
queosk/src/main/java/com/bttf/queosk/repository/MenuRepository.java
queosk/src/main/java/com/bttf/queosk/repository/OrderRepository.java
queosk/src/main/java/com/bttf/queosk/repository/RestaurantRepository.java
queosk/src/main/java/com/bttf/queosk/repository/TableRepository.java
queosk/src/main/java/com/bttf/queosk/repository/UserRepository.java
queosk/src/main/resources/application.yml
queosk/src/test/java/com/bttf/queosk/QueoskApplicationTests.java
queosk/src/test/java/com/bttf/queosk/repository/MenuRepositoryTest.java
queosk/src/test/java/com/bttf/queosk/repository/OrderRepositoryTest.java
queosk/src/test/java/com/bttf/queosk/repository/RestaurantRepositoryTest.java
queosk/src/test/java/com/bttf/queosk/repository/TableRepositoryTest.java
queosk/src/test/java/com/bttf/queosk/repository/UserRepositoryTest.java

restaurant, user, table 테이블 엔티티 및 리포지토리 추가
테이블 엔티티 및 리포지토리 추가
restaurant, user, table 테이블 엔티티 및 리포지토리 추가
없음.

Feat: 테이블 엔티티 및 리포지토리 추가

---

queosk/src/main/java/com/bttf/queosk/entity/Comment.java
queosk/src/main/java/com/bttf/queosk/entity/Menu.java
queosk/src/main/java/com/bttf/queosk/entity/Order.java
queosk/src/main/java/com/bttf/queosk/entity/Queue.java
queosk/src/main/java/com/bttf/queosk/entity/Restaurant.java
queosk/src/main/java/com/bttf/queosk/entity/Review.java
queosk/src/main/java/com/bttf/queosk/entity/Settlement.java
queosk/src/main/java/com/bttf/queosk/entity/Table.java
queosk/src/main/java/com/bttf/queosk/entity/User.java
queosk/src/main/java/com/bttf/queosk/mapper/RestaurantSignInMapper.java
queosk/src/main/java/com/bttf/queosk/repository/CommentRepository.java
queosk/src/main/java/com/bttf/queosk/repository/MenuRepository.java
queosk/src/main/java/com/bttf/queosk/repository/OrderRepository.java
queosk/src/main/java/com/bttf/queosk/repository/QueueRepository.java
queosk/src/main/java/com/bttf/queosk/repository/RestaurantRepository.java
queosk/src/main/java/com/bttf/queosk/repository/ReviewRepository.java
queosk/src/main/java/com/bttf/queosk/repository/SettlementRepository.java
queosk/src/main/java/com/bttf/queosk/repository/TableRepository.java
queosk/src/main/java/com/bttf/queosk/repository/UserRepository.java
queosk/src/main/java/com/bttf/queosk/service/RestaurantService.java
queosk/src/test/java/com/bttf/queosk/repository/CommentRepositoryTest.java
queosk/src/test/java/com/bttf/queosk/repository/MenuRepositoryTest.java
queosk/src/test/java/com/bttf/queosk/repository/OrderRepositoryTest.java
queosk/src/test/java/com/bttf/queosk/repository/QueueRepositoryTest.java
queosk/src/test/java/com/bttf/queosk/repository/RestaurantRepositoryTest.java
queosk/src/test/java/com/bttf/queosk/repository/ReviewRepositoryTest.java
queosk/src/test/java/com/bttf/queosk/repository/SettlementRepositoryTest.java
queosk/src/test/java/com/bttf/queosk/repository/TableRepositoryTest.java
queosk/src/test/java/com/bttf/queosk/repository/UserRepositoryTest.java

파일 이름 수정 및 Entity 자료형 Wrapper 형태로 수정
파일 이름 수정 및 Entity 자료형 Wrapper 형태로 수정
없음

Rename: 파일 이름 수정 및 Entity 자료형 Wrapper 형태로 수정

---

.github/workflows/add_reviewers.yml
queosk/src/main/java/com/bttf/queosk/controller/RestaurantController.java
queosk/src/main/java/com/bttf/queosk/service/RestaurantService/RestaurantService.java

Fix: 에러 수정 및 팀원 현황 변경 으로 인한 작업

---

queosk/src/main/java/com/bttf/queosk/config/WebConfig.java

WebConfig 클래스를 만들어 CORS 에러 예방
WebConfig 클래스를 만들어 CORS 에러 예방
[레퍼런스](https://velog.io/@ohzzi/CORS-%ED%97%88%EC%9A%A9-%EC%A2%80-%ED%95%B4%EC%A3%BC%EC%84%B8%EC%9A%94)
없음

feat: WebConfig 클래스를 만들어 CORS 에러 예방

---

queosk/src/main/java/com/bttf/queosk/repository/RestaurantRepository.java
queosk/src/main/java/com/bttf/queosk/service/restaurantservice/RestaurantService.java

좌표 기반 매장 검색 서비스를 가까운 순으로 정렬하게 수정
네이티브 쿼리를 사용하여 좌표 기반 매장 서비스를 가까운 순으로 정렬하게 수정하였습니다.

feat: 좌표 기반 매장 검색 서비스를 가까운 순으로 정렬하게 수정

---

queosk/src/main/java/com/bttf/queosk/controller/RestaurantController.java
queosk/src/main/java/com/bttf/queosk/dto/restaurantdto/GetRestaurantInfoMenuDto.java
queosk/src/main/java/com/bttf/queosk/service/restaurantservice/RestaurantService.java
queosk/src/test/java/com/bttf/queosk/service/RestaurantServiceTest.java

매장 정보 및 메뉴 제공 API 구현
매장 id를 입력하면 매장 정보와 매장의 메뉴를 제공하는 API를 구현하였습니다.
없음

feat: 매장 정보 및 메뉴 제공 API 구현

---

.github/workflows/github-actions.yml
queosk/Dockerfile

Dockerfile 생성 및 Github-Actions 파일 추가
Github Actions와 Docker를 사용하기 위하여
Dockerfile 생성 및 Github-Actions 파일 추가
실제 배포되는지는 main 브랜치에 올린 후 확인 가능

Feat: Dockerfile 생성 및 Github-Actions 파일 추가

---

src/test/java/com/bttf/queosk/service/orderservice/OrderServiceTest.java

주문 관련 테스트를 수정하였습니다.
주문 관련 테스트에서 빌드시 오류가 나지 않도록 수정하였습니다.
- 없음

Feat: 테스트 다시 수정

---

.idea/httpRequests/http-requests-log.http
Dockerfile
src/main/java/com/bttf/queosk/controller/KakaoPayController.java
src/main/java/com/bttf/queosk/dto/KakaoAmount.java
src/main/java/com/bttf/queosk/dto/KakaoPaymentApproveDto.java
src/main/java/com/bttf/queosk/dto/KakaoPaymentApproveForm.java
src/main/java/com/bttf/queosk/dto/KakaoPaymentCancelDto.java
src/main/java/com/bttf/queosk/dto/KakaoPaymentCancelForm.java
src/main/java/com/bttf/queosk/dto/KakaoPaymentReadyDto.java
src/main/java/com/bttf/queosk/dto/KakaoPaymentReadyForm.java
src/main/java/com/bttf/queosk/enumerate/PaymentMethodType.java
src/main/java/com/bttf/queosk/service/kakaoservice/KakaoPaymentService.java
src/test/java/com/bttf/queosk/service/orderservice/OrderServiceTest.java

카카오 페이 API 연결
카카오 페이 결제(준비, 승인), 취소 API 구현
카카오 페이 API는 처음이니 꼼꼼히 보아주십시오.

Feat: 카카오 페이 API

---

src/main/java/com/bttf/queosk/controller/SettlementController.java

LocalDateTime Format 지정 yyyy-MM-dd

Refactor: LocalDateTime Format 지정 yyyy-MM-dd

---

src/test/java/com/bttf/queosk/service/SettlementServiceTest.java

Test: settlement test 코드 작성

---

.idea/httpRequests/http-requests-log.http
src/main/java/com/bttf/queosk/controller/CommentController.java
src/main/java/com/bttf/queosk/service/CommentService.java
src/main/java/com/bttf/queosk/service/ReviewService.java
src/test/java/com/bttf/queosk/service/CommentServiceTest.java
src/test/java/com/bttf/queosk/service/ReviewServiceTest.java

리뷰, 코멘트 API, 단위 테스트 및 오류 수정
리뷰와 콘멘트 기능의 단위 테스트와 API 테스트를 수행하였습니다.
로직에 오류가 있어 이를 수정하였습니다.

Test: 리뷰, 코멘트 API, 단위 테스트 및 오류 수정

---

src/main/java/com/bttf/queosk/service/RestaurantService.java
src/test/java/com/bttf/queosk/service/MenuServiceTest.java
src/test/java/com/bttf/queosk/service/RestaurantServiceTest.java
src/test/java/com/bttf/queosk/service/ReviewServiceTest.java

RestaurantService 수정 및 테스트 수정
Slack에서 나온 오류가 나온 부분을 수정하였습니다.
없음.

Feat: RestaurantService 수정 및 테스트 수정

---

.idea/httpRequests/http-requests-log.http
src/main/java/com/bttf/queosk/dto/CommentDto.java
src/main/java/com/bttf/queosk/dto/OrderDto.java
src/main/java/com/bttf/queosk/dto/RestaurantInfoMenuGetDto.java
src/main/java/com/bttf/queosk/dto/RestaurantSignInDto.java
src/main/java/com/bttf/queosk/dto/ReviewDto.java
src/main/java/com/bttf/queosk/dto/UserSignInDto.java
src/main/java/com/bttf/queosk/service/RestaurantService.java

ID 컬럼 빠진 DTO에 ID 추가
ID 컬럼 빠진 DTO에 ID 추가
없음

Fix: ID 컬럼 빠진 DTO에 ID 추가

---

.idea/httpRequests/http-requests-log.http
build.gradle
src/main/java/com/bttf/queosk/mapper/EntityMapper.java

Mapper 클래스 삭제 및 의존성 삭제
Mapper 클래스 삭제 및 의존성 삭제
없음

Fix: Mapper 클래스 삭제 및 의존성 삭제

---

.idea/httpRequests/http-requests-log.http
src/main/java/com/bttf/queosk/config/RedisConfig.java

Fix: Redis 수정

---

src/main/java/com/bttf/queosk/config/RedisConfig.java
src/main/java/com/bttf/queosk/controller/RestaurantController.java
src/main/java/com/bttf/queosk/repository/RestaurantRepository.java

매장 api에서 생긴 문제를 수정하였습니다.
좌표를 이용한 동네 매장 찾기 API에서 비정상 활동을 한 이유인 네이티브 쿼리의 쿼리를 수정하였습니다.
또한 Redis의 주소를 localhost로 설정하고 테스트 할 경우를 위한 테스트 코드를 주석을 붙인 채 넣었습니다.
없습니다.
#102

Fix: #102번 문제 해결 및 테스트용 코드 삽입

---

src/main/java/com/bttf/queosk/config/RedisConfig.java
src/main/java/com/bttf/queosk/controller/CommentController.java
src/main/java/com/bttf/queosk/controller/RestaurantController.java
src/main/java/com/bttf/queosk/controller/ReviewController.java
src/main/java/com/bttf/queosk/dto/ReviewDto.java
src/main/java/com/bttf/queosk/repository/RestaurantRepository.java

코멘트와 리뷰 DTO 수정
코멘트와 리뷰 DTO 수정
없음

Fix: 코멘트와 리뷰 api 경로와 DTO 수정

---

src/main/java/com/bttf/queosk/controller/TableController.java
src/main/java/com/bttf/queosk/dto/TableForm.java
src/main/java/com/bttf/queosk/entity/Table.java
src/main/java/com/bttf/queosk/service/TableService.java

Controller 반환하는 값을 와일드카드가 아닌 객체를 명시하는걸로 수정 및 status setStatus로 변경

Refactor: Controller 반환하는 값을 와일드카드가 아닌 객체를 명시하는걸로 수정 및 status setter로 변경

---

src/main/java/com/bttf/queosk/service/ImageService.java

S3의 내용을 CloudFront와 Route53을 사용하여 보안을 강화시켰습니다.
이제 도메인을 쓰시는 것이 좋습니다.
일단 ip주소는 http://back.queosk.kr 로 리다이렉트 시켰습니다.

Feat: S3 보안 강화 및 엔드포인트 설정.

---

src/main/java/com/bttf/queosk/controller/KakaoLoginController.java
src/main/java/com/bttf/queosk/dto/UserSignInForm.java
src/main/java/com/bttf/queosk/service/ImageService.java
src/main/java/com/bttf/queosk/service/KakaoLoginService.java

23년 9월 7일 Dev 브랜치의 작업물을 main에 머지하여 배포

Merge: Dev to Main

---

src/main/java/com/bttf/queosk/controller/OrderController.java
src/main/java/com/bttf/queosk/controller/RestaurantController.java
src/main/java/com/bttf/queosk/enumerate/RestaurantCategory.java
src/main/java/com/bttf/queosk/service/OrderService.java
src/main/java/com/bttf/queosk/service/RestaurantService.java

금일 주문 처리 완료 리스트 확인 메소드 구현
금일 주문 처리 완료 리스트 확인 메소드 구현

Feat: 금일 주문 처리 완료 리스트 확인 메소드 구현

---

src/main/java/com/bttf/queosk/config/SecurityConfig.java

- `SecurityConfig`내부에서 각 api에 대한 접근권한(USER/RESTAURANT)을 설정
- 기존에 개발을 위해 모든 경로의 api를 허용하고있었으나 각 ROLE과 일치할때만 호출가능하도록 수정
- 필터링이 필요없는 api의 경우 `JwtFilter`에 별도로 화이트리스트 등록을 해두었습니다.

Feat: SpringSecurity 에서 각 api 접근권한 설정

---

src/main/java/com/bttf/queosk/controller/RestaurantController.java
src/main/java/com/bttf/queosk/enumerate/RestaurantCategory.java
src/main/java/com/bttf/queosk/repository/RestaurantRepository.java
src/main/java/com/bttf/queosk/service/RestaurantService.java

좌표 검색을 동네별이 아닌 카테고리별로 출력하도록 재구성

Feat: 좌표 검색을 동네별이 아닌 카테고리별로 출력하도록 재구성

---

src/main/java/com/bttf/queosk/config/SecurityConfig.java
src/main/java/com/bttf/queosk/controller/RestaurantController.java
src/main/java/com/bttf/queosk/enumerate/RestaurantCategory.java
src/main/java/com/bttf/queosk/repository/RestaurantRepository.java
src/main/java/com/bttf/queosk/service/RestaurantService.java

2023년 9월 10일 배포를 위해 Dev 브랜치를 main으로 머지함.

Merge : Dev to Main

---

src/main/java/com/bttf/queosk/config/SecurityConfig.java

- 임시로 모든 api요청에 대해 security 허용해두었습니다.
- 테스트 이슈로 인한 임시 코드 수정

Feat: SpringSecurity 임시 수정

---

src/main/java/com/bttf/queosk/config/SecurityConfig.java

* Feat: SpringSecurity 에서 각 api 접근권한 설정
* Feat: api 접근권한 설정 수정
* Fix: api 접근권한 설정 수정
임시로 모든 api에 대해 허용해두었습니다.
작업 내용을 간략하게 설명

Merge: SpringSecurity 임시 수정 (#127)

---

src/main/java/com/bttf/queosk/entity/Restaurant.java
src/main/java/com/bttf/queosk/repository/RestaurantRepository.java

쿼리 수정. (HOTFIX)
쿼리 수정. (HOTFIX)

Fix: 쿼리 수정

---

src/main/java/com/bttf/queosk/entity/Restaurant.java
src/main/java/com/bttf/queosk/repository/RestaurantRepository.java

Merge: 쿼리 수정 (#129)
Merge: 쿼리 수정 (#129)

Merge: 쿼리 수정 (#129)

---

src/main/java/com/bttf/queosk/entity/Restaurant.java
src/main/java/com/bttf/queosk/repository/RestaurantRepository.java

Fix:  2차 쿼리 수정

---

src/main/java/com/bttf/queosk/repository/RestaurantRepository.java

* Fix: 쿼리 수정
* Fix: 쿼리 수정
작업 내용을 간략하게 설명

Merge:  2차 배포

---

src/main/java/com/bttf/queosk/config/JwtFilter.java
src/main/java/com/bttf/queosk/config/JwtTokenProvider.java
src/main/java/com/bttf/queosk/config/SecurityConfig.java
src/main/java/com/bttf/queosk/dto/QueueCreateForm.java
src/main/java/com/bttf/queosk/dto/ReadInProgressOrderListForm.java
src/main/java/com/bttf/queosk/dto/ReadOrderForm.java
src/main/java/com/bttf/queosk/dto/ReadTodayOrderListForm.java
src/main/java/com/bttf/queosk/dto/RestaurantGetInfoForm.java
src/main/java/com/bttf/queosk/dto/RestaurantInfoGetCoordForm.java
src/main/java/com/bttf/queosk/dto/RestaurantInfoMenuGetForm.java
src/main/java/com/bttf/queosk/dto/RestaurantResetPasswordForm.java
src/main/java/com/bttf/queosk/dto/RestaurantSignInForm.java
src/main/java/com/bttf/queosk/dto/RestaurantSignUpForm.java
src/main/java/com/bttf/queosk/dto/RestaurantUpdatePasswordForm.java
src/main/java/com/bttf/queosk/dto/ReviewCreationForm.java
src/main/java/com/bttf/queosk/dto/SettlementForm.java
src/main/java/com/bttf/queosk/dto/SettlementPriceForm.java
src/main/java/com/bttf/queosk/dto/TableForm.java
src/main/java/com/bttf/queosk/dto/UpdateRestaurantInfoForm.java
src/main/java/com/bttf/queosk/dto/UpdateReviewForm.java
src/main/java/com/bttf/queosk/entity/Restaurant.java
src/main/java/com/bttf/queosk/enumerate/UserRole.java
src/main/java/com/bttf/queosk/service/MenuService.java
src/main/java/com/bttf/queosk/service/UserTokenDetailService.java

- `User` , `Restaurant` 각 유저 별 접근 가능 api엔드포인트를 설정했습니다.
- `SecurityConfig` 에서 커스텀 Filter만을 사용하도록 수정했습니다.
- Swagger 문서로 정의되지 않는 DTO들을 `@ApiModel` 어노테이션을 사용해 정의했습니다.
- 기타 코드 리팩토링을 진행했습니다.
- 없습니다.

Feat: Api 엔드포인트 별 권한 설정

---

src/main/java/com/bttf/queosk/controller/TableController.java

Refactor: 테이블 상태변경시 대기 순서 앞당기는 로직 추가

---

src/main/java/com/bttf/queosk/exception/ErrorCode.java

- 미정의 예외의 코드를 `400` -> `500` 으로 변경하였습니다.
- 프론트 요청사항

Feat: 정의되지 않은 예외는 예외코드 500을 반환하도록 수정

---

src/main/java/com/bttf/queosk/controller/MenuController.java

* Fix: 쿼리 수정
* Feat: 목록에서 토큰 삭제
* Feat: 목록에서 토큰 삭제
* Feat: OrderService 수정
* Feat: OrderService 수정
* HOTFIX: MenuController 수정
* HOTFIX: MenuController 수정
작업 내용을 간략하게 설명

Merge: MenuController 수정

---

src/main/java/com/bttf/queosk/config/SecurityConfig.java

* Fix: 쿼리 수정
* Feat: 목록에서 토큰 삭제
* Feat: 목록에서 토큰 삭제
* Feat: OrderService 수정
* Feat: OrderService 수정
* HOTFIX: MenuController 수정
* HOTFIX: MenuController 수정
* HOTFIX: SecurityConfig 수정
* HOTFIX: SecurityConfig 수정
작업 내용을 간략하게 설명

Merge: SecurityConfig 수정

---

src/main/java/com/bttf/queosk/controller/SettlementController.java
src/main/java/com/bttf/queosk/dto/SettlementForm.java
src/test/java/com/bttf/queosk/service/SettlementServiceTest.java

- #149 이슈 해결
- Settlement API 파라메터 타입 LocalDateTime -> LocalDate  수정
- SettlementForm 내부 메서드 수정 (싱글톤 리스트를 생성하고 있었음)
긴급 FIX 입니다. 
#149

Fix: #149 Settlement API 파라메터 타입 수정

---

src/main/java/com/bttf/queosk/controller/SettlementController.java
src/main/java/com/bttf/queosk/dto/SettlementForm.java
src/test/java/com/bttf/queosk/service/SettlementServiceTest.java

* !HOTFIX: Settlement 메서드 에러 및 파라메터 타입 수정
LocalDateTime -> LocalDate ,
SettlementForm 내부 메서드 수정
* Test: SettlementController 수정으로 인한 테스트코드 수정
작업 내용을 간략하게 설명

Fix: #149 Settlement API 파라메터 타입 수정 (#150)

---

src/main/java/com/bttf/queosk/controller/QueueController.java
src/main/java/com/bttf/queosk/controller/SettlementController.java
src/main/java/com/bttf/queosk/dto/QueueOfRestaurantDto.java
src/main/java/com/bttf/queosk/dto/QueueOfRestaurantForm.java
src/main/java/com/bttf/queosk/dto/SettlementForm.java
src/main/java/com/bttf/queosk/service/QueueService.java
src/test/java/com/bttf/queosk/service/QueueServiceTest.java
src/test/java/com/bttf/queosk/service/SettlementServiceTest.java

- 고객이 웨이팅 등록 전 선택한 가게의 웨이팅 수를 반환하는 기능 추가
- 해당 식당의 레디스의 등록된 큐 수를 확인하여 반환하는 기능을 추가했습니다.
없습니다.

Feat: 고객이 선택한 가게의 현재 웨이팅 수를 확인하는 기능 추가

---

src/main/java/com/bttf/queosk/controller/QueueController.java
src/main/java/com/bttf/queosk/dto/QueueOfRestaurantDto.java
src/main/java/com/bttf/queosk/dto/QueueOfRestaurantForm.java
src/main/java/com/bttf/queosk/service/QueueService.java
src/test/java/com/bttf/queosk/service/QueueServiceTest.java

* !HOTFIX: Settlement 메서드 에러 및 파라메터 타입 수정
LocalDateTime -> LocalDate ,
SettlementForm 내부 메서드 수정
* Test: SettlementController 수정으로 인한 테스트코드 수정
* Feat: 선택한 가게의 웨이팅 수를 확인하는 api 추가
고객이 웨이팅 등록 전 선택한 가게의 웨이팅 수를 반환하는 기능 추가
* Test: 선택한 가게의 웨이팅 수 불러오는 테스트코드 추가
작업 내용을 간략하게 설명

Merge: 고객이 선택한 가게의 현재 웨이팅 수를 확인하는 기능 추가 (#152)

---

src/main/java/com/bttf/queosk/controller/QueueController.java
src/main/java/com/bttf/queosk/controller/SettlementController.java
src/main/java/com/bttf/queosk/dto/OrderDto.java
src/main/java/com/bttf/queosk/dto/QueueOfRestaurantDto.java
src/main/java/com/bttf/queosk/dto/QueueOfRestaurantForm.java
src/main/java/com/bttf/queosk/dto/ReadInProgressOrderListForm.java
src/main/java/com/bttf/queosk/dto/ReadOrderForm.java
src/main/java/com/bttf/queosk/dto/ReadTodayOrderListForm.java
src/main/java/com/bttf/queosk/dto/SettlementForm.java
src/main/java/com/bttf/queosk/entity/Order.java
src/main/java/com/bttf/queosk/repository/OrderRepository.java
src/main/java/com/bttf/queosk/repository/SettlementQueryRepositoryImpl.java
src/main/java/com/bttf/queosk/service/OrderService.java
src/main/java/com/bttf/queosk/service/QueueService.java
src/test/java/com/bttf/queosk/service/OrderServiceTest.java
src/test/java/com/bttf/queosk/service/QueueServiceTest.java
src/test/java/com/bttf/queosk/service/SettlementServiceTest.java

- OrderEntity 와 타 엔티티간의 연관관계 해제
- Entity를 그대로 반환하던 Dto를 DTO를 반환하도록 수정
- 연관관계 수정으로 이슈를 해결하고 
- Entity를 그대로 받아 반환하던 DTO를 Dto또는 Id만을 반환하도록 수정하여 보안강화
- 수정 건과 관련해 SettlementRepositoryImpl 의 일부코드 수정 
- (메뉴 이너조인 코드 추가)
#154

Fix: #154 Menu 삭제 시 500에러 발생 이슈 해결

---

src/main/java/com/bttf/queosk/dto/OrderDto.java
src/main/java/com/bttf/queosk/dto/ReadInProgressOrderListForm.java
src/main/java/com/bttf/queosk/dto/ReadOrderForm.java
src/main/java/com/bttf/queosk/dto/ReadTodayOrderListForm.java
src/main/java/com/bttf/queosk/entity/Order.java
src/main/java/com/bttf/queosk/repository/OrderRepository.java
src/main/java/com/bttf/queosk/repository/SettlementQueryRepositoryImpl.java
src/main/java/com/bttf/queosk/service/OrderService.java
src/test/java/com/bttf/queosk/service/OrderServiceTest.java

- OrderEntity 와 타 엔티티간의 연관관계 해제
- Entity를 그대로 반환하던 Dto를 DTO를 반환하도록 수정
- 연관관계 수정으로 이슈를 해결하고 
- Entity를 그대로 받아 반환하던 DTO를 Dto또는 Id만을 반환하도록 수정하여 보안강화
- 수정 건과 관련해 SettlementRepositoryImpl 의 일부코드 수정 
- (메뉴 이너조인 코드 추가)
#154

Merge: #154 Menu 삭제 시 500에러 발생 이슈 해결 (#155)

---

src/main/java/com/bttf/queosk/repository/SettlementQueryRepositoryImpl.java
src/main/java/com/bttf/queosk/service/SettlementService.java

* Fix: 기간별, 금일 정산 시 동일 메뉴에 대한 내용이 안나오는 부분 수정
* Fix: 기간별, 금일 정산 시 동일 메뉴에 대한 내용이 안나오는 부분 수정
* Fix: 기간별, 금일 정산 시 동일 메뉴에 대한 내용이 안나오는 부분 수정
* Fix: 기간별, 금일 정산 시 동일 메뉴에 대한 내용이 안나오는 부분 수정
작업 내용을 간략하게 설명

Merge: 기간별, 금일 정산 시 동일 메뉴에 대한 내용이 안나오는 부분 수정 (#157)

---

src/main/java/com/bttf/queosk/dto/QueueIndexDto.java
src/main/java/com/bttf/queosk/repository/SettlementQueryRepositoryImpl.java
src/main/java/com/bttf/queosk/service/SettlementService.java
src/test/java/com/bttf/queosk/service/QueueServiceTest.java

Dev to Main

---

src/main/java/com/bttf/queosk/controller/QueueController.java
src/main/java/com/bttf/queosk/dto/QueueIndexDto.java
src/main/java/com/bttf/queosk/dto/QueueOfUserDto.java
src/main/java/com/bttf/queosk/dto/QueueOfUserForm.java
src/main/java/com/bttf/queosk/repository/QueueRepository.java
src/main/java/com/bttf/queosk/service/QueueService.java
src/test/java/com/bttf/queosk/service/QueueServiceTest.java

- 현재 진행중인 웨이팅 정보를 불러오는 기능 추가
- 사용자 Id로 현재 진행중에 있는 웨이팅정보(식당정보포함)을 반환하는 기능을 추가했습니다.
- 없습니다. 리뷰 잘 부탁드립니다.

Feat: 사용자가 현재진행중인 본인의 웨이팅 리스트를 조회하는 기능 추가

---

src/main/java/com/bttf/queosk/controller/RestaurantController.java
src/main/java/com/bttf/queosk/dto/KakaoPaymentReadyForm.java
src/main/java/com/bttf/queosk/dto/OrderCreationForm.java
src/main/java/com/bttf/queosk/dto/OrderDto.java
src/main/java/com/bttf/queosk/dto/ReadInProgressOrderListForm.java
src/main/java/com/bttf/queosk/dto/ReadOrderForm.java
src/main/java/com/bttf/queosk/dto/ReadTodayOrderListForm.java
src/main/java/com/bttf/queosk/entity/MenuItem.java
src/main/java/com/bttf/queosk/entity/Order.java
src/main/java/com/bttf/queosk/repository/MenuItemRepository.java
src/main/java/com/bttf/queosk/service/KakaoPaymentService.java
src/main/java/com/bttf/queosk/service/OrderService.java
src/test/java/com/bttf/queosk/service/OrderServiceTest.java

MenuItemList 및 카카오페이 API에 테이블 로직 추가
MenuItemList 및 카카오페이 API에 테이블 로직 추가

Feat: MenuItemList 및 카카오페이 API에 테이블 로직 추가

---

src/main/java/com/bttf/queosk/QueoskApplication.java
src/main/java/com/bttf/queosk/config/RedisConfig.java
src/main/java/com/bttf/queosk/service/MenuService.java
src/main/java/com/bttf/queosk/service/ReviewService.java
src/main/java/com/bttf/queosk/service/TableService.java

- 캐싱 기능 추가로 서버성능향상 및 DB 부하감소
- 리뷰/테이블/메뉴 목록 조회 시 캐싱을 사용
- 캐시 만료기간은 1일로 설정했으며 리뷰/테이블/메뉴 업데이트시에는 캐시 삭제. 
- 없습니다.

Feat: 캐싱 기능 추가로 서버성능향상 및 DB 부하감소

---

src/main/java/com/bttf/queosk/QueoskApplication.java
src/main/java/com/bttf/queosk/config/RedisConfig.java
src/main/java/com/bttf/queosk/service/MenuService.java
src/main/java/com/bttf/queosk/service/QueueService.java
src/main/java/com/bttf/queosk/service/ReviewService.java
src/main/java/com/bttf/queosk/service/TableService.java
src/main/java/com/bttf/queosk/service/UserTokenDetailService.java

Merge: Tempdev to Main

---

src/main/java/com/bttf/queosk/config/JwtFilter.java
src/main/java/com/bttf/queosk/config/SecurityConfig.java
src/main/java/com/bttf/queosk/dto/UserEditForm.java
src/main/java/com/bttf/queosk/service/UserInfoService.java

* Feat: 불필요한 필터 화이트리스트 제거
* Feat: 회원정보수정 api 호출 시 입력된 입력값에 대해서만 업데이트 진행하도록 코드수정
---------
작업 내용을 간략하게 설명

Merge: 회원정보수정 api 호출 시 입력된 입력값에 대해서만 업데이트 진행하도록 코드수정 (#177)

---

src/main/java/com/bttf/queosk/config/SecurityConfig.java
src/main/java/com/bttf/queosk/controller/RestaurantController.java
src/main/java/com/bttf/queosk/dto/RestaurantInfoGetKeywordForm.java
src/main/java/com/bttf/queosk/repository/RestaurantQueryDSLRepository.java
src/main/java/com/bttf/queosk/repository/RestaurantRepository.java
src/main/java/com/bttf/queosk/service/RestaurantService.java

* Feat: 매장 키워드 검색 추가
* Feat: 생성자 대신 RequiredArgsConstructor를 이용하여 초기화
---------
작업 내용을 간략하게 설명

Merge: 매장 키워드 검색 추가 (#179)

---

src/main/java/com/bttf/queosk/repository/RestaurantQueryDSLRepository.java

* Feat: 매장 키워드 검색 추가
* Feat: 생성자 대신 RequiredArgsConstructor를 이용하여 초기화
* Feat: 생성자 대신 RequiredArgsConstructor를 이용하여 초기화
---------
작업 내용을 간략하게 설명

Merge: 키워드 매장 검색 리팩토링 (#181)

---

src/test/java/com/bttf/queosk/service/RestaurantServiceTest.java

* Feat: 매장 키워드 검색 추가
* Feat: 생성자 대신 RequiredArgsConstructor를 이용하여 초기화
* Feat: 생성자 대신 RequiredArgsConstructor를 이용하여 초기화
* Test: 테스트 코드 변경으로 빌드 가능하도록 수정
---------
작업 내용을 간략하게 설명

Merge: 테스트 코드 변경으로 빌드 가능하도록 수정 (#183)

---

src/main/java/com/bttf/queosk/controller/UserController.java
src/main/java/com/bttf/queosk/entity/User.java
src/main/java/com/bttf/queosk/service/UserInfoService.java
src/main/java/com/bttf/queosk/service/UserLoginService.java

- 기능변경 없이 코드 가독성향상만을 위한 리팩토링입니다.
- 하드랩 너비에 맞춘 적절한 줄바꿈
- 가독성향상을 위한 메서드단위 줄바꿈
- 중복코드 제거
없습니다.

Refactor: 코드의 가독성 향상을 위한 코드 리팩터링

---

src/main/java/com/bttf/queosk/entity/MenuItem.java
src/main/java/com/bttf/queosk/repository/SettlementQueryRepositoryImpl.java

MenuItem 연관 관계 수정
MenuItem에서 Menu의 연관 관계를 ManyToOne으로 수정하였습니다.

Feat: MenuItem 연관 관계 수정

---

src/test/java/com/bttf/queosk/service/CommentServiceTest.java

* Feat: MenuItem 수정
* Feat: CommentServiceTest 코드 수정
---------
작업 내용을 간략하게 설명

Merge: CommentServiceTest 코드 수정 (#202)

---

src/main/java/com/bttf/queosk/entity/User.java
src/main/java/com/bttf/queosk/service/AutoCompleteService.java
src/main/java/com/bttf/queosk/service/UserInfoService.java
src/main/java/com/bttf/queosk/service/UserLoginService.java

- 이메일 소문자 치환 및 휴대전화번호 특수문자 제거 및 검증 추가
- 초성 검색어 자동완성 수정 (공백제거 , 초성아닌문자제거 후 조회)
- 입력받은 이메일에 대문자가 섞여있을 경우 소문자로 치환하여 조회/저장 
- 이메일은 SMTP api호출 시 사용되므로 정확한 이메일 저장 / 정확한 이메일 중복확인 필요하여 추가
- 회원정보 변경 시 숫자가 아닌 문자가 포함되어있을 경우 숫자만 남기고 제거하는 로직추가
- 기존에는 회원가입시에만 해당 로직 적용했으나 정보수정 시에도 추가
- 초성 검색 시에도 공백 및 초성이아닌문자를제거하고 메서드를 좀 더 유지보수에 유리하도록 리팩토링하였습니다.
- 회원가입/이메일중복확인 기능변경이 아닌 검증로직 추가입니다.

Feat: 회원가입 기능 개선 및 검색어 자동완성 기능 개선

---

src/main/java/com/bttf/queosk/controller/AutoCompleteController.java
src/main/java/com/bttf/queosk/controller/KakaoPayController.java
src/main/java/com/bttf/queosk/controller/OrderController.java
src/main/java/com/bttf/queosk/controller/RestaurantController.java
src/main/java/com/bttf/queosk/controller/ReviewController.java
src/main/java/com/bttf/queosk/controller/SettlementController.java
src/main/java/com/bttf/queosk/dto/ReviewCreationForm.java
src/main/java/com/bttf/queosk/dto/ReviewDto.java
src/main/java/com/bttf/queosk/entity/Review.java
src/main/java/com/bttf/queosk/entity/User.java
src/main/java/com/bttf/queosk/service/AutoCompleteService.java
src/main/java/com/bttf/queosk/service/ReviewService.java
src/main/java/com/bttf/queosk/service/UserInfoService.java
src/main/java/com/bttf/queosk/service/UserLoginService.java

- 리뷰이미지 업로드 기능 구현 
- S3 서버에 이미지업로드 시 URL반환,
이후 `ReviewCreationForm.Request` 에 해당 URL받아서 반환,
`Review` 엔티티에 저장
- hard warp 값에 맞춰 코드 줄바꿈 적용
- 없습니다.

Feat: 리뷰이미지 업로드 기능 구현 

---

src/main/java/com/bttf/queosk/config/JwtFilter.java
src/main/java/com/bttf/queosk/config/SecurityConfig.java
src/main/java/com/bttf/queosk/controller/MenuController.java
src/main/java/com/bttf/queosk/controller/ReviewController.java
src/main/java/com/bttf/queosk/controller/UserController.java
src/main/java/com/bttf/queosk/entity/KakaoAuth.java
src/main/java/com/bttf/queosk/service/KakaoLoginService.java
src/main/java/com/bttf/queosk/service/MenuService.java
src/main/java/com/bttf/queosk/service/RefreshTokenService.java

- 통합테스트 시 발견된 이슈 해결
- `JwtFilter` , `SecuritiConfig`에서 필터 적용이 필요없는 엔드포인트 재설정
- 리프레시 토큰 검색 시 Email(String)으로 검색하도록 수정
- image 업로드 시 경로 재설정
- 없습니다.
#219 , #220

Fix: 통합테스트 시 발견된 이슈 해결

---

src/main/java/com/bttf/queosk/entity/Table.java

- TableEntity 수정
- TableEntity 필드에 TableStatus @Enumerated(STRING) 어노테이션 추가

Fix: Table Entity에 Enumerated 누락되있는 부분 수정

---

src/main/java/com/bttf/queosk/config/SecurityConfig.java
src/main/java/com/bttf/queosk/dto/UserDetailsResponseForm.java
src/main/java/com/bttf/queosk/dto/UserDto.java
src/main/java/com/bttf/queosk/dto/UserEditResponseForm.java

2023년 10월 6일 매장 리뷰 리스트 열람에서 500에러가 나는 문제에 대해 수정 완료

Fix: 2023년 10월 6일 매장 리뷰 리스트 열람에서 500에러가 나는 문제에 대해 수정 완료

---

src/main/java/com/bttf/queosk/controller/SettlementController.java

* Fix: 2023년 10월 6일 매장 리뷰 리스트 열람에서 500에러가 나는 문제에 대해 수정 완료
* Fix: 코드 내 오탈자 수정 (getLocalDateTimeOfTo -> getLocalDateTimeOfFrom)
---------
작업 내용을 간략하게 설명

Merge: 코드 내 오탈자 수정 (getLocalDateTimeOfTo -> getLocalDateTimeOfFrom) (#228)

---

src/main/java/com/bttf/queosk/repository/OrderRepository.java
src/main/java/com/bttf/queosk/service/OrderService.java

금일 처리 완료한 주문만 표시되도록 변경하였습니다
작업 내용을 간략하게 설명

Merge: 매장 금일 주문 처리 완료 리스트의 로직 변경

---

src/main/java/com/bttf/queosk/dto/TableDto.java

TableDto에 Constructor 추가
#234번 이슈의 원인으로 확인 된 TableDto에 Constructor를 추가하였습니다
없습니다.
#234

Fix: TableDto에 Constructor 추가

---

src/main/java/com/bttf/queosk/controller/MenuController.java
src/main/java/com/bttf/queosk/controller/UserController.java
src/main/java/com/bttf/queosk/dto/TableDto.java
src/main/java/com/bttf/queosk/service/AutoCompleteService.java
src/main/java/com/bttf/queosk/service/KakaoLoginService.java
src/main/java/com/bttf/queosk/service/MenuService.java
src/main/java/com/bttf/queosk/service/QueueService.java
src/main/java/com/bttf/queosk/service/RefreshTokenService.java
src/main/java/com/bttf/queosk/service/UserHistoryService.java
src/main/resources/templates/verification-result.html
src/test/java/com/bttf/queosk/service/MenuServiceTest.java

2023년 10월 16일 main 브랜치를 통한 Dev 브랜치의 내용 1차 배포
#233 #235 참고
없음.
#234

Merge: 2023년 10월 16일 main 브랜치를 통한 Dev 브랜치의 내용 배포

---

src/main/java/com/bttf/queosk/controller/TableController.java
src/main/java/com/bttf/queosk/dto/TableNameUpdateForm.java
src/main/java/com/bttf/queosk/entity/Table.java
src/main/java/com/bttf/queosk/service/TableService.java
src/test/java/com/bttf/queosk/service/TableServiceTest.java

* Feat: updateTable 메소드 분리 및 수정
- TableService 코드 수정 및 리팩토링.
- TableController 코드 수정
- TableUpdateForm 생성
- 관련 테스트 코드 수정 후 테스트
- API 테스트
작업 내용을 간략하게 설명

Merge: 2023년 10월 18일 main브랜치를 통한 서버 배포

---

src/main/java/com/bttf/queosk/dto/ReviewDto.java
src/main/java/com/bttf/queosk/dto/ReviewResponseForm.java
src/test/java/com/bttf/queosk/service/ReviewServiceTest.java

2023년 10월 24일 main을 통한 배포
* Feat: ReviewDto, ReviewResponseForm 수정

Merge : 2023년 10월 24일 main을 통한 배포
